export type Animal = {
  id: number;
  name: string;
  species: 'dog' | 'cat';
  imageUrl: string;
  gender: 'male' | 'female';
  age: number;
  chipNumber: string;
  organization: string;
  phoneNumber: string;
  description: string;
  city?: string;
  status?: 'adoption' | 'lost' | 'found';
  dateOfAdmission?: string;
};

export const animals: Animal[] = [
  {
    id: 1,
    name: 'Hauczek',
    species: 'dog',
    imageUrl: '/animals/dog-1.jpg',
    gender: 'male',
    age: 3,
    chipNumber: 'CHP000001',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Energiczny i przyjazny pies, lubi dzieci i spacery.',
  },
  {
    id: 2,
    name: 'Miauczek',
    species: 'cat',
    imageUrl: '/animals/cat-1.jpg',
    gender: 'female',
    age: 2,
    chipNumber: 'CHP000002',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Cicha kotka, idealna do spokojnego domu bez innych zwierząt.',
  },
  {
    id: 3,
    name: 'Boguś',
    species: 'dog',
    imageUrl: '/animals/dog-2.jpg',
    gender: 'female',
    age: 1,
    chipNumber: 'CHP000003',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Młoda sunia, potrzebuje cierpliwego opiekuna i szkolenia.',
  },
  {
    id: 4,
    name: 'Cat-2',
    species: 'cat',
    imageUrl: '/animals/cat-2.jpg',
    gender: 'male',
    age: 4,
    chipNumber: 'CHP000004',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Towarzyski kocur, dobrze dogaduje się z innymi kotami.',
  },
  {
    id: 5,
    name: 'Dog-3',
    species: 'dog',
    imageUrl: '/animals/dog-3.jpg',
    gender: 'male',
    age: 5,
    chipNumber: 'CHP000005',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Spokojny pies średniej wielkości, lubi zabawy na podwórku.',
  },
  {
    id: 6,
    name: 'Cat-3',
    species: 'cat',
    imageUrl: '/animals/cat-3.jpg',
    gender: 'female',
    age: 3,
    chipNumber: 'CHP000006',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Lubi się tulić, idealna do mieszkania z innymi zwierzakami.',
  },
  {
    id: 7,
    name: 'Dog-4',
    species: 'dog',
    imageUrl: '/animals/dog-4.jpg',
    gender: 'female',
    age: 2,
    chipNumber: 'CHP000007',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Wesoła i aktywna, potrzebuje dużo ruchu i uwagi.',
  },
  {
    id: 8,
    name: 'Cat-4',
    species: 'cat',
    imageUrl: '/animals/cat-4.jpg',
    gender: 'male',
    age: 1,
    chipNumber: 'CHP000008',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Młody kociak, ciekawski i pełen energii.',
  },
  {
    id: 9,
    name: 'Cat-5',
    species: 'cat',
    imageUrl: '/animals/cat-5.jpg',
    gender: 'female',
    age: 6,
    chipNumber: 'CHP000009',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Starsza kotka, lubi ciszę i drzemki na parapecie.',
  },
  {
    id: 10,
    name: 'Dog-5',
    species: 'dog',
    imageUrl: '/animals/dog-1.jpg',
    gender: 'male',
    age: 4,
    chipNumber: 'CHP000010',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Posłuszny i zrównoważony pies, zna podstawowe komendy.',
  },
  {
    id: 11,
    name: 'Cat-6',
    species: 'cat',
    imageUrl: '/animals/cat-1.jpg',
    gender: 'female',
    age: 2,
    chipNumber: 'CHP000011',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Uwielbia zabawę z piórkiem i kontakt z ludźmi.',
  },
  {
    id: 12,
    name: 'Dog-6',
    species: 'dog',
    imageUrl: '/animals/dog-2.jpg',
    gender: 'female',
    age: 3,
    chipNumber: 'CHP000012',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Lubi dzieci, spokojna na smyczy, idealna dla rodziny.',
  },
];
