type Animal = {
  id: number;
  name: string;
  species: 'dog' | 'cat';
  imageUrl: string;
  gender: 'male' | 'female';
  age: number;
  chipNumber: string;
  organization: string;
  phoneNumber: string;
  description: string;
};

export const animals: Animal[] = [
  {
    id: 1,
    name: 'Dog-1',
    species: 'dog',
    imageUrl: '/animals/dog-1.jpg',
    gender: 'male',
    age: 3,
    chipNumber: 'CHP000001',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Energiczny i przyjazny pies, lubi dzieci i spacery.',
  },
  {
    id: 2,
    name: 'Cat-2',
    species: 'cat',
    imageUrl: '/animals/cat-1.jpg',
    gender: 'female',
    age: 2,
    chipNumber: 'CHP000002',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Cicha kotka, idealna do spokojnego domu bez innych zwierząt.',
  },
  {
    id: 3,
    name: 'Dog-2',
    species: 'dog',
    imageUrl: '/animals/dog-2.jpg',
    gender: 'female',
    age: 1,
    chipNumber: 'CHP000003',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Młoda sunia, potrzebuje cierpliwego opiekuna i szkolenia.',
  },
  {
    id: 4,
    name: 'Cat-2',
    species: 'cat',
    imageUrl: '/animals/cat-2.jpg',
    gender: 'male',
    age: 4,
    chipNumber: 'CHP000004',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Towarzyski kocur, dobrze dogaduje się z innymi kotami.',
  },
  {
    id: 5,
    name: 'Dog-3',
    species: 'dog',
    imageUrl: '/animals/dog-3.jpg',
    gender: 'male',
    age: 5,
    chipNumber: 'CHP000005',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Spokojny pies średniej wielkości, lubi zabawy na podwórku.',
  },
  {
    id: 6,
    name: 'Cat-3',
    species: 'cat',
    imageUrl: '/animals/cat-3.jpg',
    gender: 'female',
    age: 3,
    chipNumber: 'CHP000006',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Lubi się tulić, idealna do mieszkania z innymi zwierzakami.',
  },
  {
    id: 7,
    name: 'Dog-4',
    species: 'dog',
    imageUrl: '/animals/dog-4.jpg',
    gender: 'female',
    age: 2,
    chipNumber: 'CHP000007',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Wesoła i aktywna, potrzebuje dużo ruchu i uwagi.',
  },
  {
    id: 8,
    name: 'Cat-4',
    species: 'cat',
    imageUrl: '/animals/cat-4.jpg',
    gender: 'male',
    age: 1,
    chipNumber: 'CHP000008',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Młody kociak, ciekawski i pełen energii.',
  },
  {
    id: 9,
    name: 'Cat-5',
    species: 'cat',
    imageUrl: '/animals/cat-5.jpg',
    gender: 'female',
    age: 6,
    chipNumber: 'CHP000009',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Starsza kotka, lubi ciszę i drzemki na parapecie.',
  },
  {
    id: 10,
    name: 'Dog-5',
    species: 'dog',
    imageUrl: '/animals/dog-1.jpg',
    gender: 'male',
    age: 4,
    chipNumber: 'CHP000010',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Posłuszny i zrównoważony pies, zna podstawowe komendy.',
  },
  {
    id: 11,
    name: 'Cat-6',
    species: 'cat',
    imageUrl: '/animals/cat-1.jpg',
    gender: 'female',
    age: 2,
    chipNumber: 'CHP000011',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Uwielbia zabawę z piórkiem i kontakt z ludźmi.',
  },
  {
    id: 12,
    name: 'Dog-6',
    species: 'dog',
    imageUrl: '/animals/dog-2.jpg',
    gender: 'female',
    age: 3,
    chipNumber: 'CHP000012',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Lubi dzieci, spokojna na smyczy, idealna dla rodziny.',
  },
  {
    id: 13,
    name: 'Cat-7',
    species: 'cat',
    imageUrl: '/animals/cat-2.jpg',
    gender: 'male',
    age: 5,
    chipNumber: 'CHP000013',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Dobrze czuje się w domu z innymi kotami, bardzo łagodny.',
  },
  {
    id: 14,
    name: 'Dog-7',
    species: 'dog',
    imageUrl: '/animals/dog-3.jpg',
    gender: 'male',
    age: 2,
    chipNumber: 'CHP000014',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Wesoły psiak, potrzebuje opiekuna z doświadczeniem.',
  },
  {
    id: 15,
    name: 'Cat-8',
    species: 'cat',
    imageUrl: '/animals/cat-3.jpg',
    gender: 'female',
    age: 1,
    chipNumber: 'CHP000015',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Uwielbia się bawić, aktywna i ciekawska.',
  },
  {
    id: 16,
    name: 'Dog-8',
    species: 'dog',
    imageUrl: '/animals/dog-4.jpg',
    gender: 'female',
    age: 6,
    chipNumber: 'CHP000016',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Doświadczona, spokojna sunia – idealna dla seniora.',
  },
  {
    id: 17,
    name: 'Cat-9',
    species: 'cat',
    imageUrl: '/animals/cat-4.jpg',
    gender: 'male',
    age: 3,
    chipNumber: 'CHP000017',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Samodzielny, ale chętnie przychodzi na kolana.',
  },
  {
    id: 18,
    name: 'Cat-10',
    species: 'cat',
    imageUrl: '/animals/cat-5.jpg',
    gender: 'female',
    age: 2,
    chipNumber: 'CHP000018',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description:
      'Zrównoważona i czuła kotka, świetnie adaptuje się w nowym otoczeniu.',
  },
  {
    id: 19,
    name: 'Cat-19',
    species: 'cat',
    imageUrl: '/animals/cat-1.jpg',
    gender: 'male',
    age: 1,
    chipNumber: 'CHP000019',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Niezależna, ale potrafi się przytulać.',
  },
  {
    id: 20,
    name: 'Dog-20',
    species: 'dog',
    imageUrl: '/animals/dog-3.jpg',
    gender: 'female',
    age: 9,
    chipNumber: 'CHP000020',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Lubi aportować i bawić się piłką.',
  },
  {
    id: 21,
    name: 'Dog-21',
    species: 'dog',
    imageUrl: '/animals/dog-4.jpg',
    gender: 'female',
    age: 8,
    chipNumber: 'CHP000021',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Spokojny i posłuszny, idealny do domu z dziećmi.',
  },
  {
    id: 22,
    name: 'Cat-22',
    species: 'cat',
    imageUrl: '/animals/cat-3.jpg',
    gender: 'female',
    age: 6,
    chipNumber: 'CHP000022',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Lubi wspinaczkę i obserwację przez okno.',
  },
  {
    id: 23,
    name: 'Dog-23',
    species: 'dog',
    imageUrl: '/animals/dog-2.jpg',
    gender: 'female',
    age: 9,
    chipNumber: 'CHP000023',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Spokojny i posłuszny, idealny do domu z dziećmi.',
  },
  {
    id: 24,
    name: 'Dog-24',
    species: 'dog',
    imageUrl: '/animals/dog-4.jpg',
    gender: 'male',
    age: 1,
    chipNumber: 'CHP000024',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Spokojny i posłuszny, idealny do domu z dziećmi.',
  },
  {
    id: 25,
    name: 'Cat-25',
    species: 'cat',
    imageUrl: '/animals/cat-3.jpg',
    gender: 'male',
    age: 2,
    chipNumber: 'CHP000025',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Niezależna, ale potrafi się przytulać.',
  },
  {
    id: 26,
    name: 'Cat-26',
    species: 'cat',
    imageUrl: '/animals/cat-3.jpg',
    gender: 'female',
    age: 4,
    chipNumber: 'CHP000026',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Czuła kotka, dobrze dogaduje się z innymi zwierzętami.',
  },
  {
    id: 28,
    name: 'Cat-28',
    species: 'cat',
    imageUrl: '/animals/cat-4.jpg',
    gender: 'female',
    age: 10,
    chipNumber: 'CHP000028',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Lubi wspinaczkę i obserwację przez okno.',
  },
  {
    id: 29,
    name: 'Dog-29',
    species: 'dog',
    imageUrl: '/animals/dog-4.jpg',
    gender: 'female',
    age: 9,
    chipNumber: 'CHP000029',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Spokojny i posłuszny, idealny do domu z dziećmi.',
  },
  {
    id: 30,
    name: 'Cat-30',
    species: 'cat',
    imageUrl: '/animals/cat-3.jpg',
    gender: 'male',
    age: 9,
    chipNumber: 'CHP000030',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Niezależna, ale potrafi się przytulać.',
  },
  {
    id: 31,
    name: 'Dog-31',
    species: 'dog',
    imageUrl: '/animals/dog-1.jpg',
    gender: 'male',
    age: 5,
    chipNumber: 'CHP000031',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Aktywny pies, lubi długie spacery.',
  },
  {
    id: 32,
    name: 'Cat-32',
    species: 'cat',
    imageUrl: '/animals/cat-2.jpg',
    gender: 'female',
    age: 3,
    chipNumber: 'CHP000032',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Spokojna i łagodna, idealna do rodziny.',
  },
  {
    id: 33,
    name: 'Dog-33',
    species: 'dog',
    imageUrl: '/animals/dog-3.jpg',
    gender: 'female',
    age: 7,
    chipNumber: 'CHP000033',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Lubi bawić się z dziećmi, posłuszny.',
  },
  {
    id: 34,
    name: 'Cat-34',
    species: 'cat',
    imageUrl: '/animals/cat-1.jpg',
    gender: 'male',
    age: 2,
    chipNumber: 'CHP000034',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Ciekawski kociak, energiczny i ciekawski.',
  },
  {
    id: 35,
    name: 'Dog-35',
    species: 'dog',
    imageUrl: '/animals/dog-2.jpg',
    gender: 'male',
    age: 4,
    chipNumber: 'CHP000035',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Lubi aportować, potrzebuje dużo ruchu.',
  },
  {
    id: 36,
    name: 'Cat-36',
    species: 'cat',
    imageUrl: '/animals/cat-4.jpg',
    gender: 'female',
    age: 5,
    chipNumber: 'CHP000036',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Czuła kotka, lubi drzemki na słońcu.',
  },
  {
    id: 37,
    name: 'Dog-37',
    species: 'dog',
    imageUrl: '/animals/dog-1.jpg',
    gender: 'female',
    age: 6,
    chipNumber: 'CHP000037',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Wierna i spokojna sunia, idealna dla rodziny.',
  },
  {
    id: 38,
    name: 'Cat-38',
    species: 'cat',
    imageUrl: '/animals/cat-3.jpg',
    gender: 'male',
    age: 8,
    chipNumber: 'CHP000038',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Niezależny kocur, lubi samotność.',
  },
  {
    id: 39,
    name: 'Dog-39',
    species: 'dog',
    imageUrl: '/animals/dog-4.jpg',
    gender: 'male',
    age: 3,
    chipNumber: 'CHP000039',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Energetyczny i wesoły pies, potrzebuje uwagi.',
  },
  {
    id: 40,
    name: 'Cat-40',
    species: 'cat',
    imageUrl: '/animals/cat-5.jpg',
    gender: 'female',
    age: 7,
    chipNumber: 'CHP000040',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Łagodna i przyjazna kotka, lubi towarzystwo.',
  },
  {
    id: 41,
    name: 'Dog-41',
    species: 'dog',
    imageUrl: '/animals/dog-2.jpg',
    gender: 'female',
    age: 5,
    chipNumber: 'CHP000041',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Lubi długie spacery i zabawy na świeżym powietrzu.',
  },
  {
    id: 42,
    name: 'Cat-42',
    species: 'cat',
    imageUrl: '/animals/cat-1.jpg',
    gender: 'male',
    age: 6,
    chipNumber: 'CHP000042',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Spokojny kocur, idealny do mieszkania w bloku.',
  },
  {
    id: 43,
    name: 'Dog-43',
    species: 'dog',
    imageUrl: '/animals/dog-3.jpg',
    gender: 'male',
    age: 7,
    chipNumber: 'CHP000043',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Posłuszny pies, wymaga regularnego szkolenia.',
  },
  {
    id: 44,
    name: 'Cat-44',
    species: 'cat',
    imageUrl: '/animals/cat-4.jpg',
    gender: 'female',
    age: 3,
    chipNumber: 'CHP000044',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Aktywna i ciekawska kotka, lubi zabawy.',
  },
  {
    id: 45,
    name: 'Dog-45',
    species: 'dog',
    imageUrl: '/animals/dog-1.jpg',
    gender: 'male',
    age: 8,
    chipNumber: 'CHP000045',
    organization: 'Happy Paws',
    phoneNumber: '512345678',
    description: 'Wesoły i energiczny pies, uwielbia dzieci.',
  },
  {
    id: 46,
    name: 'Cat-46',
    species: 'cat',
    imageUrl: '/animals/cat-2.jpg',
    gender: 'female',
    age: 4,
    chipNumber: 'CHP000046',
    organization: 'Animal Aid',
    phoneNumber: '780334455',
    description: 'Spokojna i przyjazna kotka, dobrze znosi inne zwierzęta.',
  },
  {
    id: 47,
    name: 'Dog-47',
    species: 'dog',
    imageUrl: '/animals/dog-4.jpg',
    gender: 'female',
    age: 6,
    chipNumber: 'CHP000047',
    organization: 'Whisker Haven',
    phoneNumber: '600112233',
    description: 'Energetyczna sunia, potrzebuje dużo ruchu i zabawy.',
  },
];
